"""Fetcher tests using generated bytes and injected HTTP/browser mocks only."""

import gzip
from collections.abc import Mapping
from pathlib import Path

import pytest
import requests

from crawler.fetcher import Fetcher
from crawler.result import FetchResult

SAMPLES = Path(__file__).resolve().parents[1] / "html_samples"


class FakeResponse:
    """Minimal requests response mock."""

    def __init__(
        self,
        status_code: int,
        url: str,
        *,
        content: bytes = b"",
        headers: Mapping[str, str] | None = None,
        encoding: str | None = None,
    ) -> None:
        self.status_code = status_code
        self.url = url
        self.content = content
        self.headers = headers or {}
        self.encoding = encoding


class FakeClient:
    """Queue responses or exceptions and record requests."""

    def __init__(self, *outcomes: FakeResponse | requests.RequestException) -> None:
        self.outcomes = list(outcomes)
        self.calls: list[str] = []

    def get(
        self,
        url: str,
        *,
        timeout: float,
        allow_redirects: bool,
        headers: Mapping[str, str],
    ) -> FakeResponse:
        """Return the next injected outcome without network access."""
        self.calls.append(url)
        outcome = self.outcomes.pop(0)
        if isinstance(outcome, requests.RequestException):
            raise outcome
        assert timeout == 4
        assert allow_redirects is False
        assert headers["User-Agent"] == "test-crawler"
        return outcome


class FakeRobots:
    """Configurable robots checker mock."""

    def __init__(self, denied: set[str] | None = None) -> None:
        self.denied = denied or set()
        self.checked: list[str] = []

    def can_fetch(self, url: str) -> bool:
        """Record and decide access."""
        self.checked.append(url)
        return url not in self.denied


class FakeLimiter:
    """Non-sleeping rate limiter mock."""

    def __init__(self) -> None:
        self.urls: list[str] = []

    def wait(self, url: str, delay_seconds: float | None = None) -> None:
        """Record an eligible request."""
        self.urls.append(url)


class FakeBrowser:
    """Injected browser fallback mock."""

    def __init__(self) -> None:
        self.calls: list[tuple[str, float]] = []

    def fetch(self, url: str, timeout_seconds: float) -> FetchResult:
        """Return a deterministic raw browser result."""
        self.calls.append((url, timeout_seconds))
        return FetchResult(
            url,
            url + "/browser",
            200,
            {"content-type": "text/html; charset=utf-8"},
            b"browser source",
            from_playwright=True,
        )


def make_fetcher(
    client: FakeClient,
    *,
    robots: FakeRobots | None = None,
    browser: FakeBrowser | None = None,
) -> tuple[Fetcher, FakeRobots, FakeLimiter]:
    """Build a fully injected Fetcher test subject."""
    checker = robots or FakeRobots()
    limiter = FakeLimiter()
    fetcher = Fetcher(
        checker,
        limiter,
        client=client,
        playwright=browser,
        user_agent="test-crawler",
        timeout_seconds=4,
    )
    return fetcher, checker, limiter


def test_robots_denial_prevents_http_request() -> None:
    url = "https://company.example.jp/private"
    client = FakeClient()
    fetcher, _, limiter = make_fetcher(client, robots=FakeRobots({url}))

    result = fetcher.fetch(url)

    assert result.error == "robots_denied"
    assert result.status_code is None
    assert client.calls == []
    assert limiter.urls == []


@pytest.mark.parametrize("status", [429, 404])
def test_returns_non_success_status_without_browser_fallback(status: int) -> None:
    url = "https://company.example.jp/page"
    client = FakeClient(FakeResponse(status, url, content=b"response"))
    browser = FakeBrowser()
    fetcher, _, _ = make_fetcher(client, browser=browser)

    result = fetcher.fetch(url)

    assert result.status_code == status
    assert result.content == b"response"
    assert result.from_playwright is False
    assert browser.calls == []


def test_403_uses_injected_playwright_fallback() -> None:
    url = "https://company.example.jp/protected"
    browser = FakeBrowser()
    fetcher, _, _ = make_fetcher(FakeClient(FakeResponse(403, url)), browser=browser)

    result = fetcher.fetch(url)

    assert result.status_code == 200
    assert result.from_playwright is True
    assert result.final_url.endswith("/browser")
    assert browser.calls == [(url, 4)]


def test_timeout_is_returned_as_transport_error() -> None:
    url = "https://company.example.jp/slow"
    fetcher, _, _ = make_fetcher(FakeClient(requests.Timeout("fixture timeout")))

    result = fetcher.fetch(url)

    assert result.status_code is None
    assert result.error == "timeout"


def test_redirect_is_manual_and_rechecks_robots_and_rate_limit() -> None:
    start = "https://company.example.jp/start"
    final = "https://other.example.jp/final"
    client = FakeClient(
        FakeResponse(302, start, headers={"Location": final}),
        FakeResponse(200, final, content=b"final"),
    )
    fetcher, robots, limiter = make_fetcher(client)

    result = fetcher.fetch(start)

    assert result.status_code == 200
    assert result.final_url == final
    assert result.redirect_chain == (final,)
    assert robots.checked == [start, final]
    assert limiter.urls == [start, final]
    assert client.calls == [start, final]


def test_redirect_to_robots_denied_target_is_not_requested() -> None:
    start = "https://company.example.jp/start"
    denied = "https://other.example.jp/private"
    client = FakeClient(FakeResponse(302, start, headers={"location": denied}))
    fetcher, _, _ = make_fetcher(client, robots=FakeRobots({denied}))

    result = fetcher.fetch(start)

    assert result.error == "robots_denied"
    assert result.redirect_chain == (denied,)
    assert client.calls == [start]


def test_gzip_fixture_is_decompressed() -> None:
    url = "https://company.example.jp/compressed"
    compressed = gzip.compress("圧縮された本文".encode())
    response = FakeResponse(200, url, content=compressed, headers={"Content-Encoding": "gzip"})
    fetcher, _, _ = make_fetcher(FakeClient(response))

    result = fetcher.fetch(url)

    assert result.text == "圧縮された本文"


def test_content_type_encoding_decodes_fixture() -> None:
    url = "https://company.example.jp/japanese"
    source = (SAMPLES / "encoded_shift_jis.txt").read_text(encoding="utf-8")
    content = source.encode("shift_jis")
    response = FakeResponse(
        200,
        url,
        content=content,
        headers={"Content-Type": "text/plain; charset=shift_jis"},
    )
    fetcher, _, _ = make_fetcher(FakeClient(response))

    result = fetcher.fetch(url)

    assert result.encoding == "shift_jis"
    assert result.text == "東京都千代田区の会社案内\n"
